### ISSUE TITLE
Nájsť API na sťahovanie dát z trhu

### ISSUE THREAD

**Issue by Stevk0** [Libertas-Software/LFX-Trading-Platform#4]
Možnosti:
- Lemon.markets
- Alpaca.markets

Podľa výkonu sa rozhodneme medzi týmito dvoma možnosťami

**Comment by michaljano** [comment]
Nakoniec zatiaľ sme sa rozhodli pre Alpaca.markets boli na nich lepšie recenzie a ľahšie čitateľná dokumentácia
