### ISSUE TITLE
Prepočítvanie exchange rates / stoplossov / take profitov/ lotov / pipov

### ISSUE THREAD

**Issue by Stevk0** [Libertas-Software/LFX-Trading-Platform#5]

**Comment by Stevk0** [comment]
Vymyslenie spôsobu prepočítavania dát z API na uživateľom čítateľné dáta

**Comment by tomas002342** [comment]
System prepocitania hotovy len potrebujem vediet ako bude fungovat to API

**Comment by Stevk0** [comment]
Vsetko vybavene
